apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- name: minhduc857/hello-world
  newName: minhduc857/hello-world
  newTag: 3a914f544d6f1c42bb0141b7ea83d8f7ba7d2620
